language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  - source .travis/maven_settings.sh
  - mvn compile

# The install and script defaults for Java are given at
# https://docs.travis-ci.com/user/languages/java/
# For a maven project with pom.xml, these are:
#install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#script: mvn test -B

after_success:
  - mvn cobertura:cobertura coveralls:report

